apiVersion: v1
kind: ServiceAccount
metadata:
  name: tackle-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tackle-operator
  labels:
    app.kubernetes.io/name: tackle-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: tackle
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tackle-operator
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tackle-operator
    spec:
      serviceAccount: tackle-operator
      containers:
      - name: tackle-operator
        image: quay.io/{user}/tackle-operator:1.0.0-SNAPSHOT-native
        imagePullPolicy: Always
        env:
          - name: JAVA_OPERATOR_SDK_CHECK_CRD
            value: 'false'
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /q/health
            port: 8080
          initialDelaySeconds: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /q/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tackle-operator-admin
subjects:
- kind: ServiceAccount
  name: tackle-operator
roleRef:
  kind: Role
  name: tackle-operator
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tackle-operator
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  - services
  - configmaps
  - secrets
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - tackle.io
  resources:
  - tackles
  - tackles/finalizers
  - tackles/status
  verbs:
  - '*'
- apiGroups:
    - apps
    - extensions
  resources:
    - deployments
  verbs:
    - '*'
- apiGroups:
    - networking.k8s.io
  resources:
    - ingresses
  verbs:
    - '*'
- apiGroups:
    - route.openshift.io
  resources:
    - routes
  verbs:
    - '*'
