apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloaks.tackle.io
spec:
  group: tackle.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                restImage:
                  description: URL for the Rest image
                  type: string
                postgreSQLImage:
                  description: URL for the PostgreSQL image
                  type: string
                databaseSchema:
                  description: Name of the database schema
                  type: string
              required:
                - restImage
                - postgreSQLImage
                - databaseSchema
            status:
              type: object
              properties:
                conditions:
                  items:
                    properties:
                      lastTransitionTime:
                        type: string
                      message:
                        type: string
                      observedGeneration:
                        type: integer
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                    required:
                      - status
                      - type
                      - lastTransitionTime
                    type: object
                  type: array
      subresources:
        status: { }
  scope: Namespaced
  names:
    plural: keycloaks
    singular: keycloak
    kind: Keycloak
    shortNames:
      - kc
