apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: uis.tackle.io
spec:
  group: tackle.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  description: URL of the UI image
                  type: string
                controlsApiUrl:
                  description: URL of the Rest Controls backend
                  type: string
                applicationInventoryApiUrl:
                  description: URL of the Rest Application Inventory backend
                  type: string
                pathfinderApiUrl:
                  description: URL of the Rest Pathfinder backend
                  type: string
                ssoApiUrl:
                  description: URL of the Rest SSO
                  type: string
              required:
                - image
                - controlsApiUrl
                - applicationInventoryApiUrl
                - pathfinderApiUrl
                - ssoApiUrl
            status:
              type: object
              properties:
                conditions:
                  items:
                    properties:
                      lastTransitionTime:
                        type: string
                      message:
                        type: string
                      observedGeneration:
                        type: integer
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                    required:
                      - status
                      - type
                      - lastTransitionTime
                    type: object
                  type: array
      subresources:
        status: { }
  scope: Namespaced
  names:
    plural: uis
    singular: ui
    kind: Ui
    shortNames:
      - ui
